propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  cliente:
    _attributes: { phpName: Cliente }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre_razon_social: { phpName: NombreRazonSocial, type: VARCHAR, size: '256', required: true }
    contacto: { phpName: Contacto, type: VARCHAR, size: '256', required: false }
    calle: { phpName: Calle, type: VARCHAR, size: '128', required: false }
    numero_ext_int: { phpName: NumeroExtInt, type: VARCHAR, size: '16', required: false }
    colonia: { phpName: Colonia, type: VARCHAR, size: '128', required: false }
    cp: { phpName: Cp, type: INTEGER, required: false }
    telefono: { phpName: Telefono, type: VARCHAR, size: '12', required: false }
    celular: { phpName: Celular, type: INTEGER, required: false }
    correo_electronico: { phpName: CorreoElectronico, type: VARCHAR, size: '128', required: false }
  factura_cliente:
    _attributes: { phpName: FacturaCliente }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    id_cliente: { phpName: IdCliente, type: INTEGER, required: true, foreignTable: cliente, foreignReference: id, onDelete: RESTRICT, onUpdate: CASCADE }
    razon_social: { phpName: RazonSocial, type: VARCHAR, size: '128', required: true }
    rfc: { phpName: Rfc, type: VARCHAR, size: '15', required: false }
    contacto_seguimiento: { phpName: ContactoSeguimiento, type: VARCHAR, size: '256', required: false }
    calle: { phpName: Calle, type: VARCHAR, size: '64', required: false }
    numero_ext_int: { phpName: NumeroExtInt, type: VARCHAR, size: '16', required: false }
    colonia: { phpName: Colonia, type: VARCHAR, size: '64', required: false }
    municipio: { phpName: Municipio, type: VARCHAR, size: '64', required: false }
    estado: { phpName: Estado, type: VARCHAR, size: '128', required: false }
    pais: { phpName: Pais, type: VARCHAR, size: '128', required: false }
    telefono: { phpName: Telefono, type: INTEGER, required: false }
    segundo_telefono: { phpName: SegundoTelefono, type: INTEGER, required: false }
    correo_electronico: { phpName: CorreoElectronico, type: VARCHAR, size: '128', required: false }
    segmento: { phpName: Segmento, type: VARCHAR, size: '32', required: false }
    acercamiento: { phpName: Acercamiento, type: VARCHAR, size: '64', required: false }
