# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
sf_guard_plugin:
  signin_form:                  sfGuardLoginForm
  success_signout_url:          '@homepage'
  remember_key_expiration_age:  86400 # 1 day
  routes_register: false
  sf_upload_dira: uploads

sf_guard_extra_plugin:
        mail_from:        abricolabs@gmail.com
        name_from:        Abraham Rico Moreno
        subject_confirm:  Confirmación de registro
        subject_complete: Petición completa
        subject_request:  Petición de reestablecimiento de contraseña
        subject_success:  Contraseña reestablecida satisfactorimente
        admin_mail_from:  linuxska@gmail.com
        admin_name_from:  Abraham Rafael Rico Moreno